apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-example-app-deployment
spec:
  selector:
    matchLabels:
      app: python-example-app
  replicas: 1
  template:
    metadata:
      labels:
        app: python-example-app
    spec:
      containers:
      - name: python-example-app
        image: python-example-app:0.1.0
        ports:
        - containerPort: 3000
